### PR TITLE
Add some syntactic sugar around type checking

### PR DESCRIPTION
**Pull request by erayd**
## What
Add some syntactic sugar around type checking.

## Why
Because it makes life a little simpler in situations where there are *lots* of different type checks being implemented.

### CODE REVIEW

**Comment by shmax** [comment]
Whatcha makin'?

**Comment by erayd** [comment]
Yet another iteration of my compiling validator.... I think this is something like the sixth rewrite now? Have tried a number of different designs, and think I finally have one I'm happy with.

**Comment by shmax** [comment]
Ooh, so this is a part of the speedy generated validator thing we were dreaming about?

**Comment by erayd** [comment]
Yup.

**Comment by erayd** [comment]
I figure this part of it is useful enough in its own right to be worth splitting it into a separate project, hence this repo.

**Comment by shmax** [comment]
Lovin' it. 👍

**Pull request merged**
